version: '3.8'

services:
  mongodb:
    container_name: "notification_mongodb"
    image: mongo:6-jammy
    ports:
      - '27017:27017'

  prometheus:
    container_name: notification_prometheus
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    volumes:
      - "./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  localstack:
    container_name: "notification_localstack"
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"
    volumes:
      - "./etc/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"