server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: notification-logs-dev
    static_configs:
      - targets:
        - localhost
        labels:
          app: not-fy
          env: dev
          __path__: /var/logs/notification/notification-dev.log

  - job_name: notification-logs-prod
    static_configs:
      - targets:
        - localhost
        labels:
          app: not-fy
          env: prod
          __path__: /var/logs/notification/notification-prod.log

  - job_name: notification-logs
    static_configs:
      - targets:
        - localhost
        labels:
          app: not-fy
          env: prod
          __path__: /var/logs/notification/notification.log
