spring:
  application:
    name: not-fy
    env: prod

app:
  datasource:
    mongodb:
      url: ${MONGODB_URL}
  aws:
    sqs:
      endpoint: ${SQS_ENDPOINT}
      configs:
        - queue: notification-send-notification
          handler: SendNotificationHandler
  notification:
    gateway: WEB_CLIENT

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

server:
  shutdown: graceful

logging:
  level:
    com.bso.notification.infra.sqs: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    name: logs/notification-prod.log
