app:
  datasource:
    mongodb:
      url: mongodb://localhost:27017/notification
  aws:
    sqs:
      endpoint: ${SQS_ENDPOINT:http://localhost:4566}
      configs:
        - queue: notification-send-notification
          handler: SendNotificationHandler
  notification:
    gateway: WEB_CLIENT

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

server:
  shutdown: graceful

logging:
  level:
    com.bso.notification.infra.sqs: INFO