apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: Zipkin
    uid: zipkin
    type: zipkin
    orgId: 1
    access: proxy
    url: http://zipkin:9411
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: app
            value: app
          - key: env
            value: env
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} |= "$${__trace.traceId}"'
